services:
  - type: web
    name: auctrail-website
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    autoDeployTrigger: commit
    
    routes:
      - type: redirect
        source: /test-site/faq/*
        destination: /faq/
      - type: redirect
        source: /test-site/pricing/*
        destination: /pricing/
      - type: redirect
        source: /test-site/contact/*
        destination: /contact/
      - type: redirect
        source: /test-site/demo/*
        destination: /demo/
      - type: redirect
        source: /test-site/*
        destination: /
      - type: redirect
        source: /plans/*
        destination: /pricing/
      - type: redirect
        source: /support/*
        destination: /contact/
      - type: redirect
        source: /technical-support/*
        destination: /contact/
      - type: redirect
        source: /organization-setup/*
        destination: /contact/
      - type: redirect
        source: /agency-setup/*
        destination: /contact/
      - type: redirect
        source: /preview-progress/*
        destination: /
      - type: redirect
        source: /under-development/*
        destination: /
