import type { Metadata } from "next";
import Link from "next/link";
import styles from "../service-pages.module.css";

export const metadata: Metadata = { title: "Agency Setup", description: "Auctrail agency setup and onboarding for municipalities and public agencies, including departments, users, roles, data import, labels, reporting, and workflow configuration.", alternates: { canonical: "https://auctrail.com/agency-setup" } };

const setupSteps = [
  ["01", "Agency structure", "Identify the agency, departments, divisions, and the staff who will be responsible for surplus and disposition work."],
  ["02", "Users and roles", "Establish the initial users and assign access based on each person's operational responsibilities."],
  ["03", "Current workflow", "Review how property is received, approved, prepared, sold or otherwise disposed, picked up, documented, and closed today."],
  ["04", "Existing data", "Determine what active records should be entered or imported and whether historical information needs to be retained in Auctrail."],
  ["05", "Labels and field use", "Plan label printing, QR access, tablet or desktop use, and the practical process staff will follow around stored property."],
  ["06", "Launch and adoption", "Confirm the initial configuration, provide plan-appropriate onboarding, and begin using Auctrail with a controlled operational rollout."],
];

function Arrow() { return <svg aria-hidden="true" viewBox="0 0 20 20"><path d="M4 10h11M11 5l5 5-5 5" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" /></svg>; }
function Header() { return <header className="marketing-header"><div className="marketing-shell header-inner"><Link className="header-logo" href="/"><img src="/auctrail-logo-approved.jpg" alt="Auctrail" width="425" height="115" /></Link><nav className="desktop-nav"><Link href="/">Home</Link><Link href="/plans">Plans</Link><Link href="/technical-support">Technical support</Link><Link href="/support">Support</Link></nav><div className="header-actions"><a className="button button-primary button-compact" href="https://app.auctrail.com/login">Client login</a></div></div></header>; }
function Footer() { return <footer className="marketing-footer"><div className="marketing-shell footer-bottom"><span>© {new Date().getFullYear()} Auctrail. All rights reserved.</span><Link href="/support">Support center</Link></div></footer>; }

export default function AgencySetupPage() {
  return <main className={`marketing-site ${styles.site}`}><Header />
    <section className={styles.hero}><div className={`marketing-shell ${styles.heroInner}`}><p className="section-kicker">Auctrail onboarding</p><h1>Set up the agency around the way surplus work actually happens.</h1><p>Auctrail setup establishes departments, users, roles, existing data, labels, reporting needs, and the agency's intake-to-closeout process before routine use begins.</p><div className={styles.actions}><Link className="button button-primary" href="/plans">Review plans <Arrow /></Link><Link className="button button-secondary" href="/support">Start a setup conversation <Arrow /></Link></div></div></section>
    <section className={styles.section}><div className="marketing-shell"><div className={styles.heading}><div><p className="section-kicker">Setup process</p><h2>A controlled path from initial configuration to operational use.</h2></div><p>The goal is not to force an agency into a generic process. Setup maps Auctrail's structure to the people, departments, records, and disposition practices the agency already has.</p></div><div className={styles.grid}>{setupSteps.map(([n,t,d]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
    <section className={styles.dark}><div className={`marketing-shell ${styles.twoColumn}`}><div><p className="section-kicker light">What to have ready</p><h2>A few decisions make setup substantially faster.</h2><p>Agencies do not need perfect data before beginning. A clear picture of the current process is more useful than trying to redesign everything before Auctrail is configured.</p></div><div className={styles.checkPanel}><strong>Recommended setup information</strong><ul><li>Agency and department names</li><li>Initial user list and responsibilities</li><li>Current surplus forms or spreadsheets</li><li>Typical approval process</li><li>Disposition methods currently used</li><li>Examples of labels or asset identifiers</li><li>Reporting and export requirements</li><li>GovDeals account status, if applicable</li></ul></div></div></section>
    <section className={styles.section}><div className="marketing-shell"><div className={styles.heading}><div><p className="section-kicker">Setup by plan</p><h2>The software is the same. The amount of setup assistance changes.</h2></div><p>Both plans include the complete Auctrail platform. Professional includes more hands-on assistance because larger multi-department deployments usually require more configuration work.</p></div><div className={styles.planPair}><article><span>Essential · $99/month</span><h3>Guided setup</h3><p>Up to five active users and five departments, with setup guidance and import templates for a smaller implementation.</p></article><article><span>Professional · $199/month</span><h3>Assisted setup</h3><p>Up to twenty active users and unlimited departments, with an assisted onboarding session and initial data-import assistance.</p></article></div></div></section>
    <section className={styles.section}><div className={`marketing-shell ${styles.notice}`}><div><p className="section-kicker">GovDeals users</p><h2>Confirm Bulk Asset Upload before planning the export workflow.</h2><p>GovDeals Bulk Asset Upload is account-enabled and may not be active by default. The agency's authorized GovDeals account must have that capability enabled by GovDeals before using an Auctrail GovDeals-compatible export for bulk upload.</p></div><Link className="button button-primary" href="/technical-support">Technical support <Arrow /></Link></div></section>
    <Footer /></main>;
}
