import Link from "next/link";

function ArrowIcon() { return <svg aria-hidden="true" viewBox="0 0 20 20"><path d="M4 10h11M11 5l5 5-5 5" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" /></svg>; }
function CheckIcon() { return <svg aria-hidden="true" viewBox="0 0 20 20"><path d="m4 10 4 4 8-9" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" /></svg>; }

export default function SupportPage() {
  return <main className="support-site"><header className="marketing-header"><div className="marketing-shell header-inner"><Link className="header-logo" href="/" aria-label="Auctrail home"><img src="/auctrail-logo-approved.jpg" alt="Auctrail — Government Surplus Sales Software" width="425" height="115" /></Link><nav className="desktop-nav" aria-label="Primary navigation"><Link href="/#platform">Platform</Link><Link href="/#workflow">Workflow</Link><Link href="/plans">Plans</Link><Link href="/#integrations">Integrations</Link><Link href="/faq">FAQ</Link><Link href="/support" aria-current="page">Support</Link></nav><div className="header-actions support-header-actions"><a className="text-link" href="https://app.auctrail.com/login">Client login</a><Link className="button button-primary button-compact" href="/support">Request information</Link></div><details className="mobile-nav"><summary aria-label="Open navigation">Menu</summary><div className="mobile-nav-panel"><Link href="/#platform">Platform</Link><Link href="/#workflow">Workflow</Link><Link href="/plans">Plans</Link><Link href="/#integrations">Integrations</Link><Link href="/faq">FAQ</Link><Link href="/support">Support</Link><a href="https://app.auctrail.com/login">Client login</a></div></details></div></header>
  <section className="support-main"><div className="marketing-shell"><div className="support-intro"><p className="section-kicker">Support and access</p><h1>Start with the type of help you need.</h1><p>Access the Auctrail application, review onboarding information, read common questions, or find the correct path for surplus-sales platform support and agency setup.</p></div><div className="support-card-grid">
  <article className="support-card-new"><span>01</span><h2>Client access</h2><p>Sign in to your agency workspace to manage surplus-sale records, departments, reports, auction preparation, and completed sale history.</p><a className="button button-primary" href="https://app.auctrail.com/login">Open client login <ArrowIcon /></a></article>
  <article className="support-card-new"><span>02</span><h2>Technical support</h2><p>Application issues, account access, exports, labels, QR workflows, and hosted-environment assistance.</p><Link className="button button-secondary" href="/technical-support">Technical support <ArrowIcon /></Link></article>
  <article className="support-card-new"><span>03</span><h2>Agency setup</h2><p>Onboarding, departments, user roles, surplus-sale data import, label workflows, reporting, and your agency's current sales process.</p><Link className="button button-secondary" href="/agency-setup">Agency setup <ArrowIcon /></Link></article></div>
  <div className="support-note"><CheckIcon /><div><strong>GovDeals bulk-upload prerequisite</strong><br />GovDeals Bulk Asset Upload is an account-enabled feature and may not be active by default. The agency's authorized GovDeals account must have that capability enabled by GovDeals before using an Auctrail GovDeals-compatible export.</div></div></div></section>
  <footer className="marketing-footer"><div className="marketing-shell footer-bottom"><span>© {new Date().getFullYear()} Auctrail. All rights reserved.</span><span><Link href="/faq">FAQ</Link> · <Link href="/">Return to Auctrail.com</Link></span></div></footer></main>;
}
